export const VENUES = [
  {
    key: "home",
    label: "가정집",
    icon: "Home",
    blurb: "아이와 반려동물이 생활하는 공간까지 고려해 냄새와 노출을 줄인 방식으로 관리합니다.",
  },
  {
    key: "store",
    label: "외식/매장",
    icon: "Store",
    blurb: "영업 흐름을 방해하지 않도록 방문 시간을 조율하고, 위생 신뢰도를 높이는 관리를 제안합니다.",
  },
  {
    key: "office",
    label: "사무실",
    icon: "Building2",
    blurb: "근무 공간, 탕비실, 창고를 함께 점검해 쾌적한 업무 환경을 유지합니다.",
  },
  {
    key: "warehouse",
    label: "창고/물류",
    icon: "Warehouse",
    blurb: "적재 공간과 출입구 주변의 침입, 서식 경로를 집중적으로 점검합니다.",
  },
  {
    key: "public",
    label: "공공시설",
    icon: "Landmark",
    blurb: "일정과 안전 기준을 맞춰 민원 부담을 줄이는 정기 위생 관리를 돕습니다.",
  },
]

export const SERVICES_DATA = [
  {
    slug: "roach",
    icon: "Bug",
    initial: "바",
    title: "바퀴벌레 방제",
    shortDesc: "침입 경로와 서식지를 찾아 재발 가능성을 낮춥니다.",
    heroDesc:
      "배수구, 주방, 틈새 등 바퀴벌레가 숨어드는 지점을 확인하고 공간에 맞는 약제와 트랩을 병행합니다.",
    process: [
      { title: "현장 진단", desc: "서식 흔적과 침입 경로를 먼저 확인합니다." },
      { title: "맞춤 시공", desc: "주방, 배수구, 틈새 중심으로 안전한 약제를 적용합니다." },
      { title: "사후 확인", desc: "재발 가능 지점을 안내하고 필요 시 추가 관리를 제안합니다." },
    ],
    venues: {
      home: { relevant: true, note: "주방과 욕실 주변을 중심으로 아이와 반려동물이 있는 집도 안심할 수 있게 관리합니다." },
      store: { relevant: true, note: "음식점과 매장은 영업 전후 시간대에 맞춰 위생 리스크를 줄입니다." },
      office: { relevant: true, note: "탕비실, 창고, 배수 라인을 함께 점검합니다." },
      warehouse: { relevant: true, note: "적재물 주변과 출입구 틈새를 집중 점검합니다." },
      public: { relevant: true, note: "방문 일정과 안전 고지를 맞춰 진행합니다." },
    },
    faq: [
      { q: "약제 냄새가 많이 나나요?", a: "공간과 상황에 맞춰 노출과 냄새를 줄인 방식으로 안내합니다." },
      { q: "한 번 방문으로 끝나나요?", a: "발생 정도에 따라 다르며, 필요하면 사후 관리 일정을 제안합니다." },
    ],
  },
  {
    slug: "rat",
    icon: "Rat",
    initial: "쥐",
    title: "쥐 방제",
    shortDesc: "침입로 차단과 트랩 관리로 재발을 예방합니다.",
    heroDesc: "쥐의 이동 흔적, 배설물, 외부 유입 지점을 확인해 차단과 포획 관리를 함께 진행합니다.",
    process: [
      { title: "침입 경로 확인", desc: "외벽, 배관, 환기구 등 유입 가능 지점을 점검합니다." },
      { title: "차단/트랩 설치", desc: "노출을 줄인 위치에 트랩과 차단 조치를 적용합니다." },
      { title: "재점검", desc: "흔적 변화를 확인하고 재발 방지 방법을 안내합니다." },
    ],
    venues: {
      home: { relevant: true, note: "가정에서는 아이와 반려동물의 안전을 고려해 트랩 노출을 최소화합니다." },
      store: { relevant: true, note: "식자재 보관 공간과 후면 출입구를 우선 점검합니다." },
      office: { relevant: false, note: "창고나 탕비실에서 흔적이 있을 때 진단을 권장합니다." },
      warehouse: { relevant: true, note: "대형 출입문, 하역장, 적재 공간의 유입 지점을 관리합니다." },
      public: { relevant: true, note: "공공시설 기준에 맞춰 안전하게 진행합니다." },
    },
    faq: [{ q: "쥐가 다시 들어오지 않게 할 수 있나요?", a: "주요 침입로를 차단하면 재발 가능성을 크게 낮출 수 있습니다." }],
  },
  {
    slug: "flying-insect",
    icon: "Wind",
    initial: "날",
    title: "모기/파리 방제",
    shortDesc: "발생원 점검과 정기 관리로 여름철 불편을 줄입니다.",
    heroDesc: "배수구, 물 고임, 외부 유입 동선을 확인해 날벌레 발생을 줄이는 방제 서비스를 제공합니다.",
    process: [
      { title: "발생원 확인", desc: "배수구, 화분, 외부 출입문 등 발생 가능 지점을 찾습니다." },
      { title: "방제 시공", desc: "실내외 동선을 고려해 필요한 지점에 시공합니다." },
      { title: "정기 관리", desc: "계절과 발생 빈도에 맞춰 방문 주기를 제안합니다." },
    ],
    venues: {
      home: { relevant: true, note: "베란다, 욕실, 배수구 주변을 중심으로 관리합니다." },
      store: { relevant: true, note: "외부 좌석과 주방 배수 라인이 있는 매장에 효과적입니다." },
      office: { relevant: false, note: "실내 식물이나 배수구 주변 발생 시 점검합니다." },
      warehouse: { relevant: true, note: "하역장과 출입문 주변의 유입 경로를 확인합니다." },
      public: { relevant: false, note: "실외 이용 시설은 정기 방문을 권장합니다." },
    },
    faq: [{ q: "여름에만 관리하면 되나요?", a: "발생 전 예방 관리가 더 효과적입니다." }],
  },
  {
    slug: "disinfection",
    icon: "SprayCan",
    initial: "소",
    title: "소독/방역",
    shortDesc: "감염병 예방과 위생 관리를 위한 전문 소독입니다.",
    heroDesc: "다중 이용 공간, 매장, 사무실, 가정에 필요한 소독 범위와 동선을 정해 안전하게 진행합니다.",
    process: [
      { title: "공간 확인", desc: "소독이 필요한 구역과 이용 동선을 확인합니다." },
      { title: "전문 소독", desc: "장비와 약제를 공간 특성에 맞춰 적용합니다." },
      { title: "결과 안내", desc: "작업 범위와 다음 권장 시기를 안내합니다." },
    ],
    venues: {
      home: { relevant: true, note: "가정 내 위생 관리가 필요한 시기에 권장합니다." },
      store: { relevant: true, note: "매장 위생 신뢰를 위해 정기 관리 이력을 만들 수 있습니다." },
      office: { relevant: true, note: "직원이 많은 공간은 정기 소독으로 관리합니다." },
      warehouse: { relevant: true, note: "작업자 출입이 잦은 창고와 물류 공간에 적합합니다." },
      public: { relevant: true, note: "공공시설 일정에 맞춰 방문합니다." },
    },
    faq: [{ q: "소독 확인서가 필요한가요?", a: "필요한 경우 상담 시 요청해 주세요." }],
  },
  {
    slug: "air-quality",
    icon: "AirVent",
    initial: "공",
    title: "실내 공기질 관리",
    shortDesc: "냄새와 곰팡이 원인을 찾아 쾌적한 공간을 만듭니다.",
    heroDesc: "환기, 습도, 곰팡이 발생 지점을 확인해 실내 공기질을 개선하는 관리를 제안합니다.",
    process: [
      { title: "원인 진단", desc: "냄새, 습도, 환기 상태를 확인합니다." },
      { title: "제거/처리", desc: "오염 지점을 정리하고 필요한 처리를 진행합니다." },
      { title: "예방 안내", desc: "환기와 습도 관리 방법을 안내합니다." },
    ],
    venues: {
      home: { relevant: true, note: "곰팡이와 냄새가 반복되는 공간에 적합합니다." },
      store: { relevant: false, note: "매장 냄새 이슈가 있을 때 별도 진단을 권장합니다." },
      office: { relevant: false, note: "환기가 어려운 공간을 중심으로 점검합니다." },
      warehouse: { relevant: true, note: "습도 관리가 필요한 창고에 도움이 됩니다." },
      public: { relevant: false, note: "다중 이용 시설도 진단 가능합니다." },
    },
    faq: [{ q: "곰팡이가 다시 생기지 않나요?", a: "원인까지 함께 안내해 재발 가능성을 낮춥니다." }],
  },
  {
    slug: "mattress",
    icon: "BedDouble",
    initial: "매",
    title: "매트리스 청소",
    shortDesc: "보이지 않는 먼지와 진드기까지 관리합니다.",
    heroDesc: "전문 장비로 매트리스의 먼지와 진드기 원인을 줄여 수면 공간을 쾌적하게 관리합니다.",
    process: [
      { title: "상태 확인", desc: "오염도와 소재를 확인합니다." },
      { title: "전문 장비 청소", desc: "먼지와 미세 오염을 제거합니다." },
      { title: "건조/마감", desc: "충분히 마감한 뒤 사용 안내를 드립니다." },
    ],
    venues: {
      home: { relevant: true, note: "침실과 아이 방 매트리스를 중심으로 관리합니다." },
      store: { relevant: false, note: "숙박업소는 별도 견적을 안내합니다." },
      office: { relevant: false, note: "숙직실이 있는 경우 문의해 주세요." },
      warehouse: { relevant: false, note: "해당 사항이 적은 서비스입니다." },
      public: { relevant: false, note: "기숙 시설은 문의해 주세요." },
    },
    faq: [{ q: "청소 후 바로 사용할 수 있나요?", a: "작업 방식에 따라 건조 시간을 안내합니다." }],
  },
  {
    slug: "water-tank",
    icon: "Droplets",
    initial: "물",
    title: "물탱크 청소",
    shortDesc: "저수조를 세척하고 깨끗한 물 사용 환경을 지킵니다.",
    heroDesc: "저수조 내부 오염을 확인하고 세척, 소독, 마감 확인까지 진행합니다.",
    process: [
      { title: "저수조 점검", desc: "내부 상태와 작업 조건을 확인합니다." },
      { title: "세척/소독", desc: "전문 장비로 내부를 세척하고 소독합니다." },
      { title: "수질 확인", desc: "작업 후 상태를 확인하고 안내합니다." },
    ],
    venues: {
      home: { relevant: false, note: "공동주택은 관리사무소와 일정 조율이 필요합니다." },
      store: { relevant: true, note: "정기 청소 의무가 있는 업종은 이력 관리가 중요합니다." },
      office: { relevant: true, note: "건물 저수조의 정기 청소 일정을 관리합니다." },
      warehouse: { relevant: true, note: "시설 규모에 맞춰 방문 견적을 안내합니다." },
      public: { relevant: true, note: "법정 주기에 맞춰 진행합니다." },
    },
    faq: [{ q: "청소 주기는 어떻게 되나요?", a: "시설과 법정 기준에 맞춰 상담 시 안내합니다." }],
  },
]

export function getServiceBySlug(slug) {
  return SERVICES_DATA.find((s) => s.slug === slug)
}
